### ISSUE TITLE
(todo) generated README from template

### ISSUE THREAD

**Issue by probablyup** [probablyup/buttermilk#1]
- [ ] use `react-docgen` or something like it to scan the components file and extract some useful info
- [ ] convert the README into a template that interpolates the result of docgen to fill in the various sections
- [ ] make sure the HMR experience when running the site works as expected with this strategy
